#pragma once

#define FPS			60
#define DEBUG		1
#define FIRE_FLOWER_NUM		3

#define TEXT1_X		220
#define TEXT1_Y		300
#define TEXT2_X		370
#define TEXT2_Y		300
#define TEXT_SAVE_X			200
#define TEXT_SAVE_Y			440
#define TEXT_RESET_X		320
#define TEXT_RESET_Y		440

#define RWD_VICTORY			1.0
#define RWD_DOMINANT		1.0
#define RWD_PUT				0.0
#define RWD_CAN_PUT			0.0
#define RWD_FAULT			-0.5
#define RWD_NOT_UPDATED		-100.0

#define BATTLE_PLAYER_NONE		-1
#define BATTLE_PLAYER_YELLOW	0
#define BATTLE_PLAYER_BLUE		1
#define BATTLE_PLAYER_RED		2
#define BATTLE_PLAYER_GREEN		3
#define BATTLE_PLAYER_DEER		4
#define BATTLE_PLAYER_PLAYER	5

#define SCENE_ACTION_TALK	1
#define SCENE_ACTION_MOVE	2
#define SCENE_ACTION_EXIBIT	3
#define SCENE_ACTION_LOAD	4
#define SCENE_ACTION_MUSIC	5
#define SCENE_ACTION_GRAPH	6
#define SCENE_ACTION_EQ		7
#define SCENE_ACTION_BATTLE	8
#define SCENE_ACTION_COCK	9
#define SCENE_ACTION_STOP	-1

#define SCENE_WHO_DESC		0
#define SCENE_WHO_YELLOW	1
#define SCENE_WHO_BLUE		2
#define SCENE_WHO_RED		3
#define SCENE_WHO_GREEN		4
#define SCENE_WHO_DEER		5
#define SCENE_WHO_CARD		6
#define SCENE_WHO_PLAYER	-1

#define MRK_TRIGGER_FIRED		1
#define	MRK_TRIGGER_TALK		2
#define MRK_TRIGGER_NONE		-1

#define COMMENT_CHANGE_TYPE_SEQUENTIAL		"seq"
#define COMMENT_CHANGE_TYPE_PLAY_TURN		"play"
#define COMMENT_CHANGE_TYPE_LONG_THINKING	"long"
#define COMMENT_CHANGE_TYPE_LONG_THINKING_TIME	10 * FPS

#define VICTORY_NONE		0
#define VICTORY_BLACK		1
#define VICTORY_WHITE		-1
#define VICTORY_DRAW		10

#define TEBAN_SENKO			0
#define TEBAN_KOKO			1
